config/routes.rb
Cpa::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users, :path_names =>
	{
		:sign_in => 'login',
		:sign_out => 'logout',
		:password => 'secret',
		:confirmation => 'verification',
		:unlock => 'unblock',
		:registration => 'register'
	}, :controllers => { :registrations => "my/registrations" }
              
  constraints :subdomain => "r" do
    match ':ground_id/rotator' => 'robot#rotator'
    match ':ground_id/advert' => 'robot#show'
    match ':ground_id/advert/:offer_id' => 'robot#show'
    match ':ground_id/goto/:offer_id' => 'robot#redirect'
    match ':ground_id/goto/:offer_id/:advert_id' => 'robot#redirect'
    match ':offer_id/visit' => 'robot#visit'
    match ':offer_id/target/:target_id' => 'robot#target'
    match ':offer_id/target/:target_id/:order_id' => 'robot#target'
  end

	constraints :subdomain => "my" do
	  scope :module => "my" do
			match '/' => 'base#index'
			#advertiser
			resources :offers do
				resources :targets
				resources :adverts do
					resources :banner_images
				end
				resources :grounds, :controller => "ground_offers" do
					get :accept
					get :deny
				end
			end
			#webmaster
			resources :grounds do
				resources :links, :controller => "ground_link_offers"
				resources :adverts, :controller => "ground_advert_offers"
			end
			#advertiser & webmaster
      resources :achievements do
        get :report, :on => :collection
      end
      resources :payments
      resources :stats
			resources :discussions do
				post :message
				put :close
      end
      resource :profile
      resources :payment_requests
	  end
	end

	constraints :subdomain => "admin" do
	  scope :module => "admin" do
			match '/' => 'base#index'
			resources :moderations do
				get :accept
				get :deny
			end
			resources :suspicions do
				get :block
				get :forgive
			end
			resources :discussions do
				post :message
				put :close
      end
      resources :offers
			resources :users do
        get :block

				resources :offers do
					post :update_advertiser
					resources :targets
					resources :adverts do
						resources :banner_images
					end
					resources :grounds, :controller => "ground_offers" do
						get :accept
						get :deny
					end
				end
				resources :grounds do
					post :update_webmaster
				end
        resources :payments do
          #
        end
        resource :profile
				resources :achievements do
          get :cancel
          get :report, :on => :collection
				end
			end
      resources :stats
      resources :articles
      resources :news
      resources :debtors
      resources :achievement_collection_statuses
      resources :payment_requests do
      	get :pay
      	get :cancel
      end
	  end
	end

  resources :articles
  resources :news
  resources :offers

  resources :ref, :controller => "referrals"

	root :to => 'home#index'
end

app/models/ground.rb
# coding: utf-8

class Ground
  include Mongoid::Document
	include Mongoid::Symbolize

	before_create :build_ground_rotator_config

	belongs_to :webmaster
	#field :webmaster_id, type: Fields::Serializable::ForeignKeys::Object, default: -> {current_user.id}
	belongs_to :category

	field :title, type: String, default: ''
	field :url, type: String, default: ''

  auto_increment :alternative_id
  index({alternative_id: 1 }, { unique: true })

	symbolize :type, :in => [:website, :doorway, :socialnet, :context, :email, :etc], :default => :website

	symbolize :rotator_mode, :in => [:manual, :auto], :default => :manual
	embeds_one :ground_rotator_config
	accepts_nested_attributes_for :ground_rotator_config

	field :accepted_rotator_offers_ids, type: Array, default: []
	field :denied_rotator_offers_ids, type: Array, default: []
	field :pending_rotator_offers_ids, type: Array, default: []
	field :accepted_link_offers_ids, type: Array, default: []
	field :denied_link_offers_ids, type: Array, default: []
	field :pending_link_offers_ids, type: Array, default: []

	def advert_offers_ids
    self.accepted_rotator_offers_ids+self.denied_rotator_offers_ids+self.pending_rotator_offers_ids
  end
	def advert_offers
    Offer.any_in(_id: advert_offers_ids)
  end
	def link_offers_ids
    self.accepted_link_offers_ids+self.denied_link_offers_ids+self.pending_link_offers_ids
  end
  def link_offers
    Offer.any_in(_id: link_offers_ids)
  end

	def find_offer_permission(offer_id)
		self.ground_offers.where(:offer_id => offer_id).first
	end

	def find_or_create_offer_permission(offer)
		ground_offer = find_offer_permission offer.id
		unless ground_offer
			ground_offer = self.ground_offers.new
			if offer.auto_accept_grounds
        if offer.excepted_categories.exclude?(self.category_id)
          if offer.excepted_ground_types.exclude?(self.type)
            ground_offer.state=:accepted
          end
        end
      end
			ground_offer.offer = offer
			ground_offer.save
		end
		ground_offer
	end

	def add_link_offer(offer)
		ground_offer = find_or_create_offer_permission(offer)
		case ground_offer.state
			when :accepted
				self.accepted_link_offers_ids << offer.id
			when :denied
				self.denied_link_offers_ids << offer.id
			when :pending
				self.pending_link_offers_ids << offer.id
		end
	end

	def add_link_offer_and_save(offer)
		self.add_link_offer(offer)
		self.save
	end

	def remove_link_offer(offer)
		offer_id = (offer.is_a? Offer) ? offer.id : offer
		link_offer = self.accepted_link_offers_ids.delete(offer_id)
		if link_offer
			offer = Offer.find(offer_id) unless (offer.is_a? Offer)
			UserMailer.link_offer_removing(self.webmaster, offer).deliver
		else
			link_offer = self.denied_link_offers_ids.delete(offer_id)
			link_offer = self.pending_link_offers_ids.delete(offer_id) unless link_offer
		end
		link_offer
	end

	def remove_link_offer_and_save(offer)
		remove_link_offer(offer)
		self.save
	end

	def add_rotator_offer(offer)
		ground_offer = find_or_create_offer_permission(offer)
		case ground_offer.state
			when :accepted
				self.accepted_rotator_offers_ids << offer.id
			when :denied
				self.denied_rotator_offers_ids << offer.id
			when :pending
				self.pending_rotator_offers_ids << offer.id
		end
	end

	def add_rotator_offer_and_save(offer)
		self.add_rotator_offer(offer)
		self.save
	end

	def remove_rotator_offer(offer)
		offer_id = (offer.class==Offer)? offer.id : offer
		rotator_offer = self.accepted_rotator_offers_ids.delete(offer_id)
		rotator_offer = self.denied_rotator_offers_ids.delete(offer_id) unless rotator_offer
		rotator_offer = self.pending_rotator_offers_ids.delete(offer_id) unless rotator_offer
		rotator_offer
	end

	def remove_rotator_offer_and_save(offer)
		self.remove_rotator_offer(offer)
		self.save
	end

	def remove_all_rotator_offers
		self.accepted_rotator_offers_ids.clear
		self.denied_rotator_offers_ids.clear
		self.pending_rotator_offers_ids.clear
	end


	has_many :ground_offers, dependent: :delete

	has_many :achievements

	def accepted_offers
		offers = case self.rotator_mode
			when :manual
				Offer.any_in(_id: self.accepted_rotator_offers_ids)
			when :auto
				self.ground_rotator_config.offers
      else
        Offer.all
			end
		offers.accepted
	end

	def change_webmaster!(new_webmaster)
		old_webmaster_id = self.webmaster_id
		self.webmaster = new_webmaster
		self.save!
		StatCounter.where(:ground_id => self.id, :webmaster_id => old_webmaster_id).update(webmaster_id: new_webmaster.id)
    self.achievements.update(webmaster_id: new_webmaster.id)
	end

	#validates :url, :uniqueness => true

	MODERATED_ATTRS = %w[title url type category_id]
	include IsModerated

end

app/controllers/admin/grounds_controller.rb
	# coding: utf-8

class Admin::GroundsController < Admin::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs
	before_filter :find_object, :only => [:show, :update, :edit, :destroy]
	before_filter :and_crumbs

	def index
		@grounds = @user.grounds
	end

	def show
		add_crumb "Рекламная площадка «#{@ground.title}»"
	end

	def edit
		add_crumb "Рекламная площадка «#{@ground.title}»"
	end

	def new
		@ground = @user.grounds.new
		add_crumb "Новая рекламная площадка"
	end

	def create
		@ground = @user.grounds.new(params[:ground])
		flash[:notice] = 'Площадка добавлена.' if @ground.save
		respond_with(@ground, :location => user_ground_path(@user, @ground))
	end

	def update
		@ground = Ground.find(params[:id])
		flash[:notice] = 'Площадка обновлена.' if @ground.update_attributes(params[:ground])
		respond_with(@ground, :location => user_ground_path(@user, @ground))
	end

	def destroy
		flash[:notice] = 'Площадка удалена.' if @ground.destroy
		respond_with(@ground, :location => user_grounds_path(@user))
	end

	def update_webmaster
    @ground = @user.grounds.find(params[:ground_id])
		@new_user = User.find(params[:new_user_id])
		flash[:notice] = 'Вебмастер изменён.' if @offer.change_webmaster!(@new_user)
		respond_with(@offer, :location => user_offer_path(@new_user, @offer))
	end

	protected

	def find_nested_objects
		@user = User.find(params[:user_id])
	end

	def and_nested_crumbs
		add_crumb "Пользователи", users_path
		add_crumb "Пользователь «#{@user.email}»", user_path(@user)
	end

	def find_object
		@ground = @user.grounds.find(params[:id])
	end

	def and_crumbs
		add_crumb "Рекламные площадки", user_grounds_path(@user)
	end

end

app/controllers/my/grounds_controller.rb
# coding: utf-8

class My::GroundsController < My::BaseController
	before_filter :find_object, :only => [:show, :update, :edit, :destroy]
	before_filter :and_crumbs

	def index
		@grounds = current_user.grounds
	end

	def show
		add_crumb "Рекламная площадка «#{@ground.title}»"
	end

	def edit
		add_crumb "Рекламная площадка «#{@ground.title}»"
	end

	def new
		@ground = Ground.new
		add_crumb "Новая рекламная площадка"
	end

	def create
		@ground = Ground.new(params[:ground])
		@ground.webmaster = current_user
		flash[:notice] = 'Площадка добавлена.' if @ground.save
		respond_with(@ground, :location => ground_path(@ground))
	end

	def update
		@ground = Ground.find(params[:id])
		flash[:notice] = 'Площадка обновлена.' if @ground.update_attributes(params[:ground])
		respond_with(@ground, :location => ground_path(@ground))
	end

	def destroy
		flash[:notice] = 'Площадка удалена.' if @ground.destroy
		respond_with(@ground, :location => grounds_path)
	end

	private

	def find_object
		@ground = current_user.grounds.find(params[:id])
	end

	def and_crumbs
		add_crumb "Рекламные площадки", grounds_path
	end

end

app/views/admin/grounds/_form.html.haml
= simple_form_for([@user.becomes(User), @ground], :html => {:class => 'form-horizontal' }) do |f|
	= f.input :title
	= f.input :url, :placeholder => 'http://'
	= f.input :type, :as => :select, :collection => Ground.get_type_values
	= f.input :category, :collection => Category.all, :label_method => :title, :selected => lambda { |v| v.id == f.object.category_id }
	= f.button :submit, :class => 'btn-primary'
	= link_to 'Отмена', grounds_path, :class => "btn btn-danger"

app/views/admin/grounds/index.html.haml
%table.table.table-bordered.table-striped
	%thead
		%tr
			%th= 'Название'
			%th= 'Сайт'
			%th= 'Статус'
			%th= 'Режим'
			%th= 'Действия'
	%tbody
		- @grounds.each do |ground|
			%tr{:class => ground.is_accepted? ? '' : 'muted'}
				%td= ground.title
				%td= ground.url
				%td= state_label(ground.moderated_state)
				%td= ground.rotator_mode
				%td
					= link_to user_ground_path(@user, ground), :class => 'btn btn-small' do
						%i.icon-cog
						= 'Настройки'
					= link_to edit_user_ground_path(@user, ground), :class => 'btn btn-small' do
						%i.icon-pencil
						= 'Редактировать'
					= link_to user_ground_path(@user, ground), :class => 'btn btn-small btn-danger', :method => :delete, :data => { :confirm => "Вы уверены?"} do
						%i.icon-trash.icon-white
						= 'Удалить'
= link_to new_user_ground_path(@user), :class => 'btn btn-primary' do
	%i.icon-plus-sign.icon-white
	= 'Добавить'

app/views/admin/grounds/show.html.haml
- auto_mode = (@ground.rotator_mode==:auto)
%h3= 'Настройки подбора банеров:'
= simple_form_for([@user.becomes(User), @ground], :html => {:class => 'form-horizontal' }) do |f|
	.control-group= f.input :rotator_mode, :required => true, :as => :select, :collection => Ground.get_rotator_mode_values, :input_html => { :class => "span6" }
	= f.fields_for @ground.ground_rotator_config do |cf|
		.auto_mode_fields{:style => auto_mode ? 'display:block' : 'display:none'}
			.control-group= cf.input :categories, :collection => Category.all, :input_html => { :multiple => true, :class => "span6"}
			.control-group= cf.input :block_adult, :as => :boolean, :input_html => { :class => "span6" }
			.control-group= cf.input :block_doubtful, :as => :boolean, :input_html => { :class => "span6" }
	= f.button :submit, :class => 'btn-primary'

:javascript
	$(document).ready(function() {
		$('#ground_rotator_mode').change(function () {
			var rotator_mode = $(this).val();
			var auto_mode = (rotator_mode=='auto')
			var form = $(this).closest("form");
			var auto_mode_fields = form.find('.auto_mode_fields');
			auto_mode_fields.toggle(auto_mode);
			auto_mode_fields.find('input').prop('disabled', !auto_mode);
		});
	});

%hr
= form_tag(user_ground_update_webmaster_path(@user, @ground), :method => :post) do
	Смена пользователя:
	= select_tag :new_user_id, options_from_collection_for_select(Webmaster.all, "id", "email", @ground.webmaster_id)
	= submit_tag 'Сменить!'