config/routes.rb
Cpa::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users, :path_names =>
	{
		:sign_in => 'login',
		:sign_out => 'logout',
		:password => 'secret',
		:confirmation => 'verification',
		:unlock => 'unblock',
		:registration => 'register'
	}, :controllers => { :registrations => "my/registrations" }
              
  constraints :subdomain => "r" do
    match ':ground_id/rotator' => 'robot#rotator'
    match ':ground_id/advert' => 'robot#show'
    match ':ground_id/advert/:offer_id' => 'robot#show'
    match ':ground_id/goto/:offer_id' => 'robot#redirect'
    match ':ground_id/goto/:offer_id/:advert_id' => 'robot#redirect'
    match ':offer_id/visit' => 'robot#visit'
    match ':offer_id/target/:target_id' => 'robot#target'
    match ':offer_id/target/:target_id/:order_id' => 'robot#target'
  end

	constraints :subdomain => "my" do
	  scope :module => "my" do
			match '/' => 'base#index'
			#advertiser
			resources :offers do
				resources :targets
				resources :adverts do
					resources :banner_images
				end
				resources :grounds, :controller => "ground_offers" do
					get :accept
					get :deny
				end
			end
			#webmaster
			resources :grounds do
				resources :links, :controller => "ground_link_offers"
				resources :adverts, :controller => "ground_advert_offers"
			end
			#advertiser & webmaster
      resources :achievements do
        get :report, :on => :collection
      end
      resources :payments
      resources :stats
			resources :discussions do
				post :message
				put :close
      end
      resource :profile
      resources :payment_requests
	  end
	end

	constraints :subdomain => "admin" do
	  scope :module => "admin" do
			match '/' => 'base#index'
			resources :moderations do
				get :accept
				get :deny
			end
			resources :suspicions do
				get :block
				get :forgive
			end
			resources :discussions do
				post :message
				put :close
      end
      resources :offers
			resources :users do
        get :block

				resources :offers do
					post :update_advertiser
					resources :targets
					resources :adverts do
						resources :banner_images
					end
					resources :grounds, :controller => "ground_offers" do
						get :accept
						get :deny
					end
				end
				resources :grounds do
					post :update_webmaster
				end
        resources :payments do
          #
        end
        resource :profile
				resources :achievements do
          get :cancel
          get :report, :on => :collection
				end
			end
      resources :stats
      resources :articles
      resources :news
      resources :debtors
      resources :achievement_collection_statuses
      resources :payment_requests do
      	get :pay
      	get :cancel
      end
	  end
	end

  resources :articles
  resources :news
  resources :offers

  resources :ref, :controller => "referrals"

	root :to => 'home#index'
end

app/models/achievement.rb
class Achievement
	include Mongoid::Document
	include Mongoid::Timestamps
	belongs_to :webmaster
	belongs_to :advertiser
	belongs_to :ground
	belongs_to :offer
	belongs_to :visitor
	field :target_id, type: BSON::ObjectId

	field :page, type: String
	field :ip, type: String
end

app/models/visits/achievement.rb
# coding: utf-8

class Achievement
	include Mongoid::Document
	include Mongoid::Timestamps
	include Mongoid::Symbolize
  include Mongoid::MoneyField
  include Extensions::Aggregations

  symbolize :state, :in => [:pending, :accepted, :denied], :default => :pending, :scopes => true
  symbolize :payment_state, :in => [:unpaid, :paid], :default => :unpaid, :scopes => true

	belongs_to :webmaster
	belongs_to :advertiser
	belongs_to :ground
	belongs_to :offer
	belongs_to :visitor

  field :target_id, type: Moped::BSON::ObjectId
  field :webmaster_payment_id, type: Moped::BSON::ObjectId
  field :advertiser_payment_id, type: Moped::BSON::ObjectId
  field :affiliator_payment_id, type: Moped::BSON::ObjectId

  field :accepted_at, type: DateTime

	field :page, type: String
	field :ip, type: String
  index({ip: 1}, {background: true})

  field :sub_id, type: String

  money_field :webmaster_amount
  money_field :advertiser_amount

	field :order_id, type: String #optional for manual confirmation
  field :additional_info, type: String

  field :hold_date, type: Date

	def is_accepted?
		self.state==:accepted
  end

  def build_prototype(offer, visitor, target_id)
    self.webmaster = visitor.ground.webmaster
    self.advertiser = offer.advertiser
    self.ground = visitor.ground
    self.sub_id = visitor.sub_id
    self.offer = offer
    self.visitor = visitor
    self.target_id = target_id
  end

  def pay
    return false if self.state!=:accepted || self.payment_state!=:unpaid #TODO: advanced check for state
    webmaster_amount = self.webmaster_amount
    advertiser_amount = self.advertiser_amount
    if self.advertiser.can_pay? advertiser_amount
      webmaster = self.webmaster
      webmaster.hold_balance -= webmaster_amount
      webmaster.total_payments += webmaster_amount
      webmaster.save!
      p = webmaster.payments.new(description: 'Перечисление средств за цель')
      p.amount = webmaster_amount
      p.save!
      self.webmaster_payment_id = p.id
      #
      advertiser = self.advertiser
      advertiser.hold_balance += advertiser_amount
      advertiser.total_payments += advertiser_amount
      advertiser.save!
      p = advertiser.payments.new(description: 'Перечисление средств за цель')
      p.amount = -advertiser_amount
      p.save!
      self.advertiser_payment_id = p.id
      #
      affiliator = webmaster.affiliator
      if affiliator
        payment_id = affiliator.referral_pay(webmaster_amount*0.05, :percentage)
        self.affiliator_payment_id = payment_id
      end
      #
      self.payment_state = :paid
      self.save!
    end
  end

  def accept(webmaster_amount, advertiser_amount)
    offer = self.offer
    #
    self.state = :accepted
    self.accepted_at = Time.now
    self.webmaster_amount = webmaster_amount
    self.advertiser_amount = advertiser_amount
    self.hold_date = Date.today + target.hold.days
    #
    webmaster = self.webmaster
    webmaster.hold_balance += self.webmaster_amount
    webmaster.save!
    #
    advertiser = self.advertiser
    advertiser.hold_balance -= self.advertiser_amount
    advertiser.save!
    #
    offer.payments += webmaster_amount
    offer.save

    collect_statistics
  end

  def cancel!
    if self.state==:accepted
      self.accepted_at = nil
      offer = self.offer
      webmaster = self.webmaster
      advertiser = self.advertiser
      webmaster_amount = self.webmaster_amount
      advertiser_amount = self.advertiser_amount
      #
      offer.payments -= webmaster_amount
      offer.save

      collect_statistics(true)

      case self.payment_state
      when :unpaid
        if webmaster
          webmaster.hold_balance -= self.webmaster_amount
          webmaster.save!
        end
        if advertiser
          advertiser.hold_balance += self.advertiser_amount
          advertiser.save!
        end
      when :paid
        if webmaster
          webmaster.balance -= webmaster_amount
          webmaster.total_payments -= webmaster_amount
          p = webmaster.payments.find(self.webmaster_payment_id)
          p.delete
          webmaster.save!
          #
          affiliator = webmaster.affiliator
          if affiliator && self.affiliator_payment_id
            p = advertiser.payments.find(self.affiliator_payment_id)
            affiliator_amount = p.amount
            p.delete
            advertiser.balance -= affiliator_amount
            affiliator.referral_total_payments -= affiliator_amount
            affiliator.save!
          end
        end
        if advertiser
          advertiser.balance += advertiser_amount
          advertiser.total_payments += advertiser_amount
          p = advertiser.payments.find(self.advertiser_payment_id)
          p.delete
          advertiser.save!
        end
      end
    end
    self.state = :denied
    self.save!
  end

  def target
    if offer
      offer.targets.where(:_id => self.target_id).first
    else
      nil
    end
  end

  def collect_statistics(decrease = false)
    self.created_at ||= Time.now
    #
    h = {ground_id: self.ground_id, offer_id: self.offer_id, advertiser_id: self.advertiser_id, webmaster_id: self.webmaster_id, sub_id: self.sub_id, target_id: self.target_id}
    dates = [self.created_at,  Date.new(0)]
    dates.each do |date|
      stat = StatCounter.find_or_create_by(h.merge(date: date))
      unless decrease
        stat.inc(:targets, 1)
        stat.inc(:income, self.webmaster_amount.cents)
        stat.inc(:expenditure, self.advertiser_amount.cents)
      else
        stat.inc(:targets, -1)
        stat.inc(:income, -self.webmaster_amount.cents)
        stat.inc(:expenditure, -self.advertiser_amount.cents)
      end
    end
  end
end

app/controllers/admin/achievements_controller.rb
# coding: utf-8

class Admin::AchievementsController < Admin::BaseController
	before_filter :find_nested_objects
	before_filter :and_crumbs

	def index
    @achievements = {}
    [:pending, :accepted, :denied].each do |state|
      @achievements[state] = @user.achievements.where(state: state)
    end
	end

	def show
		@achievement = @user.achievements.find(params[:id])
		add_crumb "Достижение"
	end

	def cancel
		@achievement = @user.achievements.find(params[:achievement_id])
		flash[:notice] = 'Достижение отменено.' if @achievement.cancel!
    redirect_to user_achievement_path(@user, @achievement)
	end

  def report
    add_crumb "Отчёт"

    @created_at_total = set_filter_param(true, :created_at_total, :boolean)
    @created_at_start = set_filter_param(Date.today-1.month, :created_at_start, :date)
    @created_at_stop = set_filter_param(Date.today, :created_at_stop, :date)
    #@accepted_at_start = set_filter_param(Date.today-1.month, :accepted_at_start, :date)
    #@accepted_at_stop = set_filter_param(Date.today, :accepted_at_stop, :date)
    @webmaster_id = set_filter_param((@user.class==Webmaster && !params[:webmaster_id]) ? @user.id : nil, :webmaster, :id)
    @advertiser_id = set_filter_param((@user.class==Advertiser && !params[:advertiser_id]) ? @user.id : nil, :advertiser, :id)
    @ground_id = set_filter_param(nil, :ground, :id)
    @offer_id = set_filter_param(nil, :offer, :id)
    @state = set_filter_param(nil, :state, :symbol)
    @group_by = set_filter_param(:offer_id, :group_by, :symbol)

    ct_start = date2time(@created_at_start)
    ct_stop =  date2time(@created_at_stop)+1.day-1.second
    #at_start = date2time(@accepted_at_start)
    #at_stop =  date2time(@accepted_at_stop)+1.day-1.second

    cond = {}
    unless @created_at_total
      cond[:created_at] = {'$gte' => ct_start, '$lte' => ct_stop}
    end

    cond[:webmaster_id] = @webmaster_id if @webmaster_id
    cond[:advertiser_id] = @advertiser_id if @advertiser_id
    cond[:offer_id] = @offer_id if @offer_id
    cond[:ground_id] = @ground_id if @ground_id
    cond[:state] = @state if @state

    @achievements_data = Achievement.group_by(@group_by, :sum => %w[webmaster_amount_cents advertiser_amount_cents], :push => %w[_id], :cond => cond, :sort_desc => [:_id])
  end
	
	protected

  def set_filter_param(v, name, type = :raw)
    if params[:filter] && params[:filter][name] && !params[:filter][name].empty?
      v = params[:filter][name]
      case type
        when :date
          v = Date.parse(v)
        when :symbol
          v = v.to_sym
        when :id
          v = Moped::BSON::ObjectId(v)
        when :text
          v = v.to_s
        when :boolean
          v = [true, 'true', 1, '1', 'T', 't'].include?(v.class == String ? v.downcase : v)
        when :raw
          #do nothing
      end
    end
    v
  end

  def date2time(date)
    Time.utc(date.year,date.month,date.day)
  end

	def find_nested_objects
		@user = User.find(params[:user_id])
	end

	def and_crumbs
		add_crumb "Пользователи", users_path
		add_crumb "Пользователь «#{@user.email}»", user_path(@user)
		add_crumb "Достижения целей", user_achievements_path(@user)
	end

end

app/controllers/my/achievements_controller.rb
# coding: utf-8

class My::AchievementsController < My::BaseController
	before_filter :and_crumbs

	def index
    @achievements = {}
    [:pending, :accepted, :denied].each do |state|
      @achievements[state] = current_user.achievements.where(state: state)
    end
	end

	def show
		@achievement = current_user.achievements.find(params[:id])
		add_crumb "Достижение"
	end

  def report
    add_crumb "Отчёт"

    @created_at_start = set_filter_param(Date.today-1.month, :created_at_start, :date)
    @created_at_stop = set_filter_param(Date.today, :created_at_stop, :date)
    #@accepted_at_start = set_filter_param(Date.today-1.month, :accepted_at_start, :date)
    #@accepted_at_stop = set_filter_param(Date.today, :accepted_at_stop, :date)
    @ground_id = set_filter_param(nil, :ground, :id)
    @offer_id = set_filter_param(nil, :offer, :id)
    @state = set_filter_param(nil, :state, :symbol)
    @group_by = set_filter_param(:offer_id, :group_by, :symbol)

    ct_start = date2time(@created_at_start)
    ct_stop =  date2time(@created_at_stop)+1.day-1.second
    #at_start = date2time(@accepted_at_start)
    #at_stop =  date2time(@accepted_at_stop)+1.day-1.second

    cond = {}
    cond[:created_at] = {'$gte' => ct_start, '$lte' => ct_stop}
    #cond[:accepted_at] = {'$gte' => at_start, '$lte' => at_stop}

    if current_user.class==Webmaster
      cond[:webmaster_id] = current_user.id
    elsif current_user.class==Advertiser
      cond[:advertiser_id] = current_user.id
    end
    cond[:offer_id] = @offer_id if @offer_id
    cond[:ground_id] = @ground_id if @ground_id
    cond[:state] = @state if @state

    group_by = @group_by
    if @group_by==:amount
      if current_user.class==Webmaster
        group_by = :webmaster_amount_cents
      elsif current_user.class==Advertiser
        group_by = :advertiser_amount_cents
      end
    end

    @achievements_data = Achievement.group_by(group_by, :sum => %w[webmaster_amount_cents advertiser_amount_cents], :push => %w[_id], :cond => cond, :sort_desc => [:_id])
  end

  protected

	def and_crumbs
		add_crumb "Достижения целей", achievements_path
  end

  def set_filter_param(v, name, type = :raw)
    if params[:filter] && params[:filter][name] && !params[:filter][name].empty?
      v = params[:filter][name]
      case type
        when :date
          v = Date.parse(v)
        when :symbol
          v = v.to_sym
        when :id
          v = Moped::BSON::ObjectId(v)
        when :text
          v = v.to_s
        when :boolean
          v = [true, 'true', 1, '1', 'T', 't'].include?(v.class == String ? v.downcase : v)
        when :raw
          #do nothing
      end
    end
    v
  end

  def date2time(date)
    Time.utc(date.year,date.month,date.day)
  end

end

app/views/admin/achievements/index.html.haml
%ul.nav.nav-tabs
	%li.active
		%a{"data-toggle" => "tab", :href => "#pending"}= "Ожидающие подтверждения (#{@achievements[:pending].size})"
	%li
		%a{"data-toggle" => "tab", :href => "#accepted"}= "Одобренные (#{@achievements[:accepted].size})"
	%li
		%a{"data-toggle" => "tab", :href => "#denied"}= "Отклонённые (#{@achievements[:denied].size})"
.tab-content
	- @achievements.each_key do |state|
		.tab-pane.fade{:id => state.to_s, :class => state==:pending ? 'active in' : ''}
			%table.table.table-bordered.table-striped
				%thead
					%tr
						%th= 'Оффер'
						%th= 'Цель'
						%th= 'Площадка'
						%th= 'Стоимость'
						%th= 'Состояние'
						%th= 'Дата взятия'
						- if state==:accepted
							%th= 'Дата подтверждения'
						%th= 'Номер заказа'
						%th= 'Действия'
				%tbody
					- @achievements[state].each do |achievement|
						- offer = achievement.offer
						- target = achievement.target
						- ground = achievement.ground
						- price = achievement.advertiser_amount
						%tr{:class => achievement.is_accepted? ? '' : 'muted'}
							%td= offer.title if offer
							%td= target.title if target
							%td= "#{ground.title} (#{ground.url})" if ground
							%td
								- if achievement.state==:accepted && price
									= number_to_currency(price)
								- else
									= 'н/д'
							%td= state_label achievement.state
							%td= print_datetime achievement.created_at
							- if state==:accepted
								%td= print_datetime achievement.accepted_at if achievement.accepted_at
							%td= achievement.order_id if achievement.order_id
							%td
								= link_to user_achievement_path(@user, achievement), :class => 'btn btn-small' do
									%i.icon-cog
									= 'Открыть'
%hr
= link_to report_user_achievements_path(@user), :class => 'btn' do
	%i.icon-list-alt
	= 'Отчёт'

app/views/admin/achievements/report.html.haml
.row
	.span6
		%table.table.table-striped.table-bordered.table-condensed
			%thead
				%tr
					%th= t("simple_form.options.filter.group_by.#{@group_by}")
					%th Сумма для вебмастера
					%th Сумма для рекламодателя
					%th Количество
					%th
			%tbody
				- if @achievements_data
					- total_webmaster_amount = 0
					- total_advertiser_amount = 0
					- total_count = 0
					- @achievements_data.each do |data|
						- webmaster_amount = data['webmaster_amount_cents_sum'].to_f
						- advertiser_amount = data['advertiser_amount_cents_sum'].to_f
						- ids = data['_id_push']
						- count = ids ? ids.size : 0
						- total_webmaster_amount += webmaster_amount
						- total_advertiser_amount += advertiser_amount
						- total_count += count
						%tr
							%td
								- case @group_by
									- when :created_at, :accepted_at
										= print_datetime data['_id']
									- when :webmaster_amount_cents, :advertiser_amount_cents
										= number_to_currency(data['_id']/100.0)
									- else
										- obj = @group_by.to_s.split('_').first.camelcase.constantize.where(:_id => data['_id']).first
										- if obj
											- if [:advertiser_id, :webmaster_id].include? (@group_by)
												= link_to obj.title, user_path(obj)
											- elsif @group_by==:ground_id
												= link_to obj.title, user_ground_path(obj.webmaster, obj)
											- elsif @group_by==:offer_id
												= link_to obj.title, user_offer_path(obj.advertiser, obj)
											- else
												= obj.title
							%td= number_to_currency(webmaster_amount/100.0)
							%td= number_to_currency(advertiser_amount/100.0)
							%td= count
							%td
								- if ids
									- ids.each do |id|
										= link_to 'открыть', user_achievement_path(@user, id)
					%tr
						%th Итого:
						%td= number_to_currency(total_webmaster_amount/100.0)
						%td= number_to_currency(total_advertiser_amount/100.0)
						%td= total_count
	.span3
		.well
			%b Фильтрация
			%br
			%br
			= simple_form_for :filter, :method => :get, :defaults => { :input_html => { :class => 'spanm' } } do |f|
				= f.input :created_at_total, :as => :select, :input_html => { :value => @created_at_total }, :selected => @created_at_total
				.created_at_not_total{:class =>  @created_at_total ? 'muted' : ''}
					= f.input :created_at_start, :input_html => { :value => @created_at_start, :class => 'date_picker spanm', :disabled => @created_at_total}
					= f.input :created_at_stop, :input_html => { :value => @created_at_stop, :class => 'date_picker spanm', :disabled => @created_at_total }
				-#= f.input :accepted_at_start, :input_html => { :value => @accepted_at_start, :class => 'date_picker spanm' }
				-#= f.input :accepted_at_stop, :input_html => { :value => @accepted_at_stop, :class => 'date_picker spanm' }
				= f.input :state, :collection => Achievement.get_state_values, :include_blank => true, :selected => @state
				= f.input :webmaster, :collection => Webmaster.all, :include_blank => true, :selected => @webmaster_id
				= f.input :advertiser, :collection => Advertiser.all, :include_blank => true, :selected => @advertiser_id
				= f.input :ground, :collection => Ground.all, :include_blank => true, :selected => @ground_id
				= f.input :offer, :collection => Offer.all, :include_blank => true, :selected => @offer_id
				= f.input :group_by, :collection => [:created_at, :accepted_at, :webmaster_id, :advertiser_id, :offer_id, :ground_id, :webmaster_amount_cents, :advertiser_amount_cents], :selected => @group_by

				= f.submit 'Фильтровать', :class => 'btn'

:javascript
	$(document).ready(function() {
		$('#filter_created_at_total').change(function () {
			var is_total = ($(this).val()=='true');
			$('.created_at_not_total').toggleClass('muted', is_total);
			$('.created_at_not_total input').prop('disabled', is_total);
		});
	});

app/views/admin/achievements/show.html.haml
- offer = @achievement.offer
- target = @achievement.target
- ground =  @achievement.ground
- visitor =  @achievement.visitor
- user_agent = AgentOrange::UserAgent.new(visitor.user_agent).device
- webmaster_price = @achievement.webmaster_amount
- advertiser_price = @achievement.advertiser_amount

%h3= 'Основная информация'
%b= 'Оффер:'
= offer.title if offer
%br
%b= 'Цель:'
= target.title if target
%br
%b= 'Площадка:'
= "#{ground.title} (#{ground.url})" if ground
%br
%b= 'Дата взятия:'
= print_datetime @achievement.created_at
%br
- if @achievement.state==:accepted
	%b= 'Дата подтверждения:'
	= print_datetime @achievement.accepted_at
	%br
%b= 'Стоимость (для вебмастера):'
- if @achievement.state==:accepted && webmaster_price
	= number_to_currency webmaster_price
- else
	= 'нет данных'
%br
%b= 'Стоимость (для рекламодателя):'
- if @achievement.state==:accepted && advertiser_price
	= number_to_currency advertiser_price
- else
	= 'нет данных'
%br
%b= 'Статус:'
= state_label @achievement.state
- unless @achievement.state==:denied
	= link_to 'Отменить', user_achievement_cancel_path(@user, @achievement), :class => "btn btn-danger btn-mini"
%br
- if @achievement.order_id && !@achievement.order_id.empty?
	%b= 'Номер заказа:'
	= @achievement.order_id
	%br
%br

%h3= 'Информация о посетителе'
%b= 'Браузер:'
- case user_agent.engine.browser.name
	- when 'Internet Explorer'
		= image_tag 'browsers/ie.png'
	- when 'Firefox'
		= image_tag 'browsers/firefox.png'
	- when 'Chrome'
		= image_tag 'browsers/chrome.png'
	- when 'Opera'
		= image_tag 'browsers/opera.png'
	- when 'Safari'
		= image_tag 'browsers/safari.png'
= user_agent.engine.browser
%br
%b= 'Операционная система:'
= user_agent.operating_system
- if @achievement.page && !@achievement.page.empty?
	%br
	%b= 'Страница взятия цели:'
	= @achievement.page
- if @achievement.ip && !@achievement.ip.empty?
	%br
	%b= 'IP-Адрес:'
	= @achievement.ip

- if visitor
	- if visitor.initial_page && !visitor.initial_page.empty?
		%br
		%b= 'Источник:'
		= visitor.initial_page
	%br
	%br

	%h3= 'Статистика'
	%table.table.table-bordered.table-striped
		%thead
			%tr
				%th= 'Страница'
				%th= 'IP-Адрес'
				%th= 'Дата и время'
		%tbody
			- visitor.page_visits.each do |visit|
				%tr
					%td= visit.page
					%td= visit.ip
					%td= visit.created_at