config/routes.rb
Cpa::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users, :path_names =>
	{
		:sign_in => 'login',
		:sign_out => 'logout',
		:password => 'secret',
		:confirmation => 'verification',
		:unlock => 'unblock',
		:registration => 'register'
	}, :controllers => { :registrations => "my/registrations" }
              
  constraints :subdomain => "r" do
    match ':ground_id/rotator' => 'robot#rotator'
    match ':ground_id/advert' => 'robot#show'
    match ':ground_id/advert/:offer_id' => 'robot#show'
    match ':ground_id/goto/:offer_id' => 'robot#redirect'
    match ':ground_id/goto/:offer_id/:advert_id' => 'robot#redirect'
    match ':offer_id/visit' => 'robot#visit'
    match ':offer_id/target/:target_id' => 'robot#target'
    match ':offer_id/target/:target_id/:order_id' => 'robot#target'
  end

	constraints :subdomain => "my" do
	  scope :module => "my" do
			match '/' => 'base#index'
			#advertiser
			resources :offers do
				resources :targets
				resources :adverts do
					resources :banner_images
				end
				resources :grounds, :controller => "ground_offers" do
					get :accept
					get :deny
				end
			end
			#webmaster
			resources :grounds do
				resources :links, :controller => "ground_link_offers"
				resources :adverts, :controller => "ground_advert_offers"
			end
			#advertiser & webmaster
      resources :achievements do
        get :report, :on => :collection
      end
      resources :payments
      resources :stats
			resources :discussions do
				post :message
				put :close
      end
      resource :profile
      resources :payment_requests
	  end
	end

	constraints :subdomain => "admin" do
	  scope :module => "admin" do
			match '/' => 'base#index'
			resources :moderations do
				get :accept
				get :deny
			end
			resources :suspicions do
				get :block
				get :forgive
			end
			resources :discussions do
				post :message
				put :close
      end
      resources :offers
			resources :users do
        get :block

				resources :offers do
					post :update_advertiser
					resources :targets
					resources :adverts do
						resources :banner_images
					end
					resources :grounds, :controller => "ground_offers" do
						get :accept
						get :deny
					end
				end
				resources :grounds do
					post :update_webmaster
				end
        resources :payments do
          #
        end
        resource :profile
				resources :achievements do
          get :cancel
          get :report, :on => :collection
				end
			end
      resources :stats
      resources :articles
      resources :news
      resources :debtors
      resources :achievement_collection_statuses
      resources :payment_requests do
      	get :pay
      	get :cancel
      end
	  end
	end

  resources :articles
  resources :news
  resources :offers

  resources :ref, :controller => "referrals"

	root :to => 'home#index'
end

app/models/moderations/is_moderated.rb
# coding: utf-8

module IsModerated
	extend ActiveSupport::Concern

	included do
		has_one :moderation, as: :moderated, dependent: :delete
		field :moderated_state, type: Symbol, default: :pending
    around_create :add_moderation
    around_update :set_moderation
    around_destroy :del_moderation

		scope :accepted, where(:moderated_state => :accepted)
		scope :denied,	 where(:moderated_state => :denied)
		scope :pending,  where(:moderated_state => :pending)
	end

	module ClassMethods
		def moderated_fields
			MODERATED_ATTRS
		end
	end

	def add_moderation
		moderated_fields = self.class::MODERATED_ATTRS
    self.moderated_state = :pending unless moderated_fields.empty?
    yield
    change_moderation moderated_fields, :created
  end

	def set_moderation
    changed_attrs = changes.clone
		moderated_fields = changed_attrs.keys & self.class::MODERATED_ATTRS
    self.moderated_state = :pending unless moderated_fields.empty?
    yield
    change_moderation moderated_fields, :updated
  end

	def change_moderation(moderated_fields, reason)
    return if moderated_fields.empty?
		state = :pending
		moderation = self.moderation
		unless moderation
			moderation = self.build_moderation
			if self.embedded?
				moderation.moderated_path = generate_moderated_path
			end
    end
		moderation.reason = reason
		moderation.state = state
		moderation.moderation_state_changes.build({:state => state, :reason => reason})
		moderation_field_change = moderation.moderation_field_changes.build
		moderated_fields.each do |f|
			value = self[f]
			moderation_field_change.changed_fields[f] = value
			moderation.changed_fields[f] = value
		end
		moderation.save
  end

  def del_moderation
    moderation = self.moderation
    yield
    moderation.destroy
  end

	def generate_moderated_path
		path = ''
		obj = self
		while obj.embedded?
			model_name = obj.atomic_path.split('.').last
			if self.embedded_one?
				path = ".#{model_name}#{path}"
			else
				path = ".#{model_name}.find('#{obj._id}')#{path}"
			end
			obj = obj._parent
		end
		path = "#{obj.class}.find('#{obj._id}')#{path}"
		path
	end

	def is_accepted?
		self.moderated_state == :accepted
	end

	def is_denied?
		self.moderated_state == :denied
	end

	def is_pending?
		self.moderated_state == :pending
	end

end

app/models/moderations/moderation.rb
# coding: utf-8

class Moderation
	include Mongoid::Document
	include Mongoid::Symbolize
	include Mongoid::Timestamps

	#before_create :add_initial_state_change

	belongs_to :moderated, polymorphic: true
	embeds_many :moderation_field_changes
	embeds_many :moderation_state_changes

	symbolize :state, :in => [:accepted, :denied, :pending], :scopes => true, :default => :pending
	symbolize :reason, :in => [:created, :updated], :default => :created
	field :moderated_type, type: String, default: -> { self.moderated.class.to_s }
	field :changed_fields, type: Hash, default: {}
	field :accepted_fields, type: Hash, default: {}
	field :moderated_path, type: String

	def accept(current_user, edit_fields = nil)
		state = :accepted
		self.state = state
		self.moderation_state_changes.build({:state => state, :reason => :checked, :user => current_user, :edit_fields => edit_fields})
		self.accepted_fields.merge! self.changed_fields
		self.changed_fields.clear
		self.save
		m_obj = moderated_object
		if edit_fields && !edit_fields.empty?
			edit_fields.each do |key, value|
				m_obj.send("#{key}=", value)
			end
		end
		m_obj.write_attribute(:moderated_state, state)
		m_obj.save
	end

	def deny(current_user)
		state = :denied
		self.state = state
		self.moderation_state_changes.build({:state => state, :reason => :checked, :user => current_user})
		self.save
		moderated_object.update_attribute(:moderated_state, state)
	end

	def moderated_object
		if self.moderated_path
      begin
			  eval(self.moderated_path)
      rescue Exception
        nil
      end
		else
			moderated
		end
	end
end

app/models/moderations/moderation_field_change.rb
# coding: utf-8

class ModerationFieldChange
	include Mongoid::Document

	embedded_in :moderation

	field :changed_fields, type: Hash, default: {}
	field :created_at, type: DateTime, default: -> { DateTime.now }
end

app/models/moderations/moderation_state_change.rb
# coding: utf-8

class ModerationStateChange
	include Mongoid::Document
	include Mongoid::Symbolize

	embedded_in :moderation

	field :state, type: Symbol
	field :message, type: String
	field :created_at, type: DateTime, default: -> { DateTime.now }
	symbolize :reason, :in => [:created, :updated, :checked]
	field :edit_fields, type: Hash

	belongs_to :user
end

app/controllers/admin/moderations_controller.rb
# coding: utf-8

class Admin::ModerationsController < Admin::BaseController
	before_filter :find_moderation, :only => [:show, :accept, :deny, :destroy]

	def index
		moderations = Moderation.desc(:updated_at)
		@moderations_accepted = moderations.accepted
		@moderations_denied = moderations.denied
		@moderations_pending = moderations.pending
		add_crumb "Модерации"
	end

	def show
		add_crumb "Модерации", moderations_path
		add_crumb "Модерация объекта #{@moderation.moderated_type}"
	end

	def accept
		@moderation.accept(current_user, params[:moderated_edit])
		redirect_to moderation_path(@moderation)
	end

	def deny
		@moderation.deny(current_user)
		redirect_to moderation_path(@moderation)
	end

	protected

	def find_moderation
		id = params[:id] ? params[:id] : params[:moderation_id]
		@moderation = Moderation.find(id)
	end
end

app/controllers/my/moderations_controller.rb
# coding: utf-8

class My::ModerationsController < My::BaseOperatorController
	before_filter :find_moderation, :only => [:show, :accept, :deny, :destroy]

	def index
		moderations = Moderation.order_by(:updated_at, :desc)
		@moderations_accepted = moderations.accepted
		@moderations_denied = moderations.denied
		@moderations_pending = moderations.pending
		add_crumb "Модерации"
	end

	def show
		add_crumb "Модерации", my_moderations_path
		add_crumb "Модерация объекта #{@moderation.moderated_type}"
	end

	def accept
		@moderation.accept(current_user, params[:moderated_edit])
		redirect_to my_moderation_path(@moderation)
	end

	def deny
		@moderation.deny(current_user)
		redirect_to my_moderation_path(@moderation)
	end

	protected

	def find_moderation
		id = params[:id] ? params[:id] : params[:moderation_id]
		@moderation = Moderation.find(id)
	end
end

app/views/admin/moderations/index.html.haml
.page-header
	%h1= 'Объекты для проверки'
%ul.nav.nav-tabs
	%li.active
		%a{"data-toggle" => "tab", :href => "#pending"}= 'Ожидающие'
	%li
		%a{"data-toggle" => "tab", :href => "#accepted"}= 'Одобренные'
	%li
		%a{"data-toggle" => "tab", :href => "#denied"}= 'Отклонённые'
.tab-content
	#pending.tab-pane.fade.active.in
		.page-header
			%h2
				= 'Ожидающие'
				%small= "(#{@moderations_pending.size})"
		%table.table.table-bordered.table-striped
			%thead
				%tr
					%th= 'Тип'
					%th= 'Причина'
					%th= 'Статус'
					%th= 'Дата'
					%th= 'Действия'
			%tbody
				- @moderations_pending.each do |moderation|
					%tr
						%td=t "model.#{moderation.moderated_type}"
						%td=t "common.reason.#{moderation.reason.to_s}"
						%td= state_label moderation.state
						%td= moderation.updated_at
						%td
							= link_to moderation_path(moderation), :class => 'btn btn-small' do
								%i.icon-cog
								= 'Открыть'
	#accepted.tab-pane.fade
		.page-header
			%h2
				= 'Одобренные'
				%small= "(#{@moderations_accepted.size})"
		%table.table.table-bordered.table-striped
			%thead
				%tr
					%th= 'Тип'
					%th= 'Причина'
					%th= 'Статус'
					%th= 'Дата'
					%th= 'Действия'
			%tbody
				- @moderations_accepted.each do |moderation|
					%tr
						%td=t "model.#{moderation.moderated_type}"
						%td=t "common.reason.#{moderation.reason.to_s}"
						%td= state_label moderation.state
						%td= print_datetime moderation.updated_at
						%td
							= link_to moderation_path(moderation), :class => 'btn btn-small' do
								%i.icon-cog
								= 'Открыть'
	#denied.tab-pane.fade
		.page-header
			%h2
				= 'Отклонённые'
				%small= "(#{@moderations_denied.size})"
		%table.table.table-bordered.table-striped
			%thead
				%tr
					%th= 'Тип'
					%th= 'Причина'
					%th= 'Статус'
					%th= 'Дата'
					%th= 'Действия'
			%tbody
				- @moderations_denied.each do |moderation|
					%tr
						%td=t "model.#{moderation.moderated_type}"
						%td=t "common.reason.#{moderation.reason.to_s}"
						%td= state_label moderation.state
						%td= moderation.updated_at
						%td
							= link_to moderation_path(moderation), :class => 'btn btn-small' do
								%i.icon-cog
								= 'Открыть'

app/views/admin/moderations/show.html.haml
%section
	.page-header
		%h1= "Проверка"
		- if @moderation.moderated_path && !@moderation.moderated_path.empty?
			- parent_object = eval(@moderation.moderated_path.split(".")[0..1].join('.'))
		- else
			- parent_object = @moderation.moderated_object

		- if [Ground, Offer].include? parent_object.class
			- user = case parent_object.class
				- when Ground
					- parent_object.webmaster
				- when Offer
					- parent_object.advertiser
			- user = user.becomes(User)
			%br
			Принадлежит пользователю:
			= link_to user.email, user
			%br
			Принадлежит объекту:
			= link_to t("model.#{parent_object.class.to_s}"), [user, parent_object]
	.row
		- moderated_class = @moderation.moderated_type.constantize
		- moderated_object = @moderation.moderated_object
		.span9
			- unless moderated_object
				%h2= 'Объект удалён!'
				- @moderation.destroy
			- else
				%b= 'Дата: '
				= print_datetime @moderation.updated_at
				%br
				%b= 'Статус: '
				= state_label @moderation.state
				%br
				%b= 'Причина: '
				=t "common.reason.#{@moderation.reason.to_s}"
				%br
				%b= 'Тип объекта: '
				=t "model.#{@moderation.moderated_type}"
				%hr
				- if @moderation.state==:pending
					%h2= 'Изменения'
					%table.table.table-bordered.table-striped
						%thead
							%tr
								%th= 'Поле'
								%th= 'Значение'
								%th= 'Утверждённое значение'
						%tbody
							- @moderation.changed_fields.keys.each do |key|
								- changed_value = @moderation.changed_fields[key]
								- accepted_value = @moderation.accepted_fields[key]
								- type = :default
								- if changed_value.class==Moped::BSON::ObjectId && key[-3..-1]=='_id'
									- klass = key[0..-4].camelize.constantize
									- type = :association
								- elsif moderated_class.const_defined?(:MODERATED_ATTRS_INFO) && moderated_class::MODERATED_ATTRS_INFO[key]
									- attr_info = moderated_class::MODERATED_ATTRS_INFO[key]
									- type = attr_info[:type]
								%tr
									%td
										=t "simple_form.labels.#{@moderation.moderated_type.to_s.downcase}.#{key.to_s}"
										= "(#{key.to_s})"
									%td
										- if changed_value
											- case type
												- when :association
													= klass.find(changed_value).title
												- when :carrierwave_image
													= changed_value
													%br
													- show_method = attr_info[:show_method] ? attr_info[:show_method] : key
													- img = moderated_object.send(show_method)
													- if img.present?
														= image_tag(img)
													- else
														= '-'
												- when :money
													= number_to_currency Money.new(changed_value)
												- else
													= changed_value
									%td
										- if accepted_value
											- case type
												- when :association
													= klass.find(accepted_value).title
												- when :money
													= number_to_currency Money.new(accepted_value)
												- else
													= accepted_value

					= form_tag(moderation_accept_path(@moderation), :method => :get) do
						- if defined? moderated_class::MODERATED_EDIT_FIELDS
							%h4= 'Дополнительные настройки:'
							- moderated_class::MODERATED_EDIT_FIELDS.each do |key|
								.span4
									=t "simple_form.labels.#{@moderation.moderated_type.to_s.downcase}.#{key.to_s}"
									- field_name = "moderated_edit[#{key.to_s}]"
									- if moderated_class.fields[key.to_s]
										- value = moderated_object.read_attribute(key)
										- options = moderated_class.fields[key.to_s].options
										- case options[:type].to_s
											- when 'Boolean'
												= check_box_tag field_name, 1, value
											- when 'Integer'
												= number_field_tag field_name, value, :class => 'span2'
											- when 'Float'
												= number_field_tag field_name, value, :class => 'span2', :step => 'any'
											- else
												= ''
									- else
										- value = moderated_object.send(key)
										= text_field_tag field_name, value, :class => 'span2'
							%br
							%br
						= button_tag :class => 'btn btn-success' do
							%i.icon-ok.icon-white
							= 'Одобрить'
						= link_to moderation_deny_path(@moderation), :class => 'btn btn-danger' do
							%i.icon-remove.icon-white
							= 'Отказать'
					%hr
			.row
				.span4
					%h3= 'Последние изменения'
					%table.table.table-bordered.table-striped
						%thead
							%tr
								%th= 'Дата'
								%th= 'Поля'
						%tbody
							- @moderation.moderation_field_changes.each do |change|
								%tr
									%td= change.created_at
									%td= change.changed_fields.keys.to_sentence
				.span5
					%h3= 'Последние проверки'
					%table.table.table-bordered.table-striped
						%thead
							%tr
								%th= 'Дата'
								%th= 'Статус'
								%th= 'Проверяющий'
								- if defined? moderated_class::MODERATED_EDIT_FIELDS && !moderated_class::MODERATED_EDIT_FIELDS.empty?
									%th= 'Установленные значения'
						%tbody
							- @moderation.moderation_state_changes.each do |change|
								%tr
									%td= change.created_at
									%td=t "common.state.#{change.state.to_s}"
									%td
										- user = change.user
										= link_to user.email, user_path(user) if user
									%td= change.edit_fields