config/routes.rb
Cpa::Application.routes.draw do
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :users, :path_names =>
	{
		:sign_in => 'login',
		:sign_out => 'logout',
		:password => 'secret',
		:confirmation => 'verification',
		:unlock => 'unblock',
		:registration => 'register'
	}, :controllers => { :registrations => "my/registrations" }
              
  constraints :subdomain => "r" do
    match ':ground_id/rotator' => 'robot#rotator'
    match ':ground_id/advert' => 'robot#show'
    match ':ground_id/advert/:offer_id' => 'robot#show'
    match ':ground_id/goto/:offer_id' => 'robot#redirect'
    match ':ground_id/goto/:offer_id/:advert_id' => 'robot#redirect'
    match ':offer_id/visit' => 'robot#visit'
    match ':offer_id/target/:target_id' => 'robot#target'
    match ':offer_id/target/:target_id/:order_id' => 'robot#target'
  end

	constraints :subdomain => "my" do
	  scope :module => "my" do
			match '/' => 'base#index'
			#advertiser
			resources :offers do
				resources :targets
				resources :adverts do
					resources :banner_images
				end
				resources :grounds, :controller => "ground_offers" do
					get :accept
					get :deny
				end
			end
			#webmaster
			resources :grounds do
				resources :links, :controller => "ground_link_offers"
				resources :adverts, :controller => "ground_advert_offers"
			end
			#advertiser & webmaster
      resources :achievements do
        get :report, :on => :collection
      end
      resources :payments
      resources :stats
			resources :discussions do
				post :message
				put :close
      end
      resource :profile
      resources :payment_requests
	  end
	end

	constraints :subdomain => "admin" do
	  scope :module => "admin" do
			match '/' => 'base#index'
			resources :moderations do
				get :accept
				get :deny
			end
			resources :suspicions do
				get :block
				get :forgive
			end
			resources :discussions do
				post :message
				put :close
      end
      resources :offers
			resources :users do
        get :block

				resources :offers do
					post :update_advertiser
					resources :targets
					resources :adverts do
						resources :banner_images
					end
					resources :grounds, :controller => "ground_offers" do
						get :accept
						get :deny
					end
				end
				resources :grounds do
					post :update_webmaster
				end
        resources :payments do
          #
        end
        resource :profile
				resources :achievements do
          get :cancel
          get :report, :on => :collection
				end
			end
      resources :stats
      resources :articles
      resources :news
      resources :debtors
      resources :achievement_collection_statuses
      resources :payment_requests do
      	get :pay
      	get :cancel
      end
	  end
	end

  resources :articles
  resources :news
  resources :offers

  resources :ref, :controller => "referrals"

	root :to => 'home#index'
end

app/models/advert.rb
class Advert
  include Mongoid::Document
	embedded_in :offer

	field :url, type: String
end

app/controllers/admin/adverts_controller.rb
# coding: utf-8

class Admin::AdvertsController < Admin::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs
	before_filter :find_object, :only => [:show, :update, :edit, :destroy]
	before_filter :and_crumbs, :only => [:show, :edit]

	def index
		@adverts = @offer.adverts
  end

	def create
		@type = params[:type]
		@advert = @offer.adverts.build(params[@type.underscore], @type.constantize)
		flash[:notice] = 'Объявление добавлено.' if @advert.save
		respond_with(@advert, :location => user_offer_advert_path(@user, @offer, @advert))
	end

	def update
    flash[:notice] = 'Объявление обновлено.' if @advert.update_attributes(params[@advert.class.to_s.underscore])
		respond_with(@advert, :location => user_offer_adverts_path(@user, @offer))
	end

	def destroy
		flash[:notice] = 'Объявление удалено.' if @advert.destroy
		respond_with(@advert, :location => user_offer_adverts_path(@user, @offer))
	end

  def edit
    @type = @advert.class
  end

	def new
		@type = params[:type].constantize if params[:type]
		@advert = @offer.adverts.build({}, @type)
		add_crumb "Новое объявление"
	end

	protected

	def find_nested_objects
		@user = User.find(params[:user_id])
		@offer = @user.offers.find(params[:offer_id])
	end

	def and_nested_crumbs
		add_crumb "Пользователи", users_path
		add_crumb "Пользователь «#{@user.email}»", user_path(@user)
		add_crumb "Рекламные кампании", user_offers_path(@user)
		add_crumb "Рекламная кампания «#{@offer.title}»", user_offer_path(@user, @offer)
		add_crumb "Объявления", user_offer_adverts_path(@user, @offer)
	end

	def find_object
		@advert = @offer.adverts.find(params[:id])
	end

	def and_crumbs
		add_crumb "Объявление"
	end
	
end

app/controllers/my/achievements_controller.rb
# coding: utf-8

class My::AchievementsController < My::BaseController
	before_filter :and_crumbs

	def index
    @achievements = {}
    [:pending, :accepted, :denied].each do |state|
      @achievements[state] = current_user.achievements.where(state: state)
    end
	end

	def show
		@achievement = current_user.achievements.find(params[:id])
		add_crumb "Достижение"
	end

  def report
    add_crumb "Отчёт"

    @created_at_start = set_filter_param(Date.today-1.month, :created_at_start, :date)
    @created_at_stop = set_filter_param(Date.today, :created_at_stop, :date)
    #@accepted_at_start = set_filter_param(Date.today-1.month, :accepted_at_start, :date)
    #@accepted_at_stop = set_filter_param(Date.today, :accepted_at_stop, :date)
    @ground_id = set_filter_param(nil, :ground, :id)
    @offer_id = set_filter_param(nil, :offer, :id)
    @state = set_filter_param(nil, :state, :symbol)
    @group_by = set_filter_param(:offer_id, :group_by, :symbol)

    ct_start = date2time(@created_at_start)
    ct_stop =  date2time(@created_at_stop)+1.day-1.second
    #at_start = date2time(@accepted_at_start)
    #at_stop =  date2time(@accepted_at_stop)+1.day-1.second

    cond = {}
    cond[:created_at] = {'$gte' => ct_start, '$lte' => ct_stop}
    #cond[:accepted_at] = {'$gte' => at_start, '$lte' => at_stop}

    if current_user.class==Webmaster
      cond[:webmaster_id] = current_user.id
    elsif current_user.class==Advertiser
      cond[:advertiser_id] = current_user.id
    end
    cond[:offer_id] = @offer_id if @offer_id
    cond[:ground_id] = @ground_id if @ground_id
    cond[:state] = @state if @state

    group_by = @group_by
    if @group_by==:amount
      if current_user.class==Webmaster
        group_by = :webmaster_amount_cents
      elsif current_user.class==Advertiser
        group_by = :advertiser_amount_cents
      end
    end

    @achievements_data = Achievement.group_by(group_by, :sum => %w[webmaster_amount_cents advertiser_amount_cents], :push => %w[_id], :cond => cond, :sort_desc => [:_id])
  end

  protected

	def and_crumbs
		add_crumb "Достижения целей", achievements_path
  end

  def set_filter_param(v, name, type = :raw)
    if params[:filter] && params[:filter][name] && !params[:filter][name].empty?
      v = params[:filter][name]
      case type
        when :date
          v = Date.parse(v)
        when :symbol
          v = v.to_sym
        when :id
          v = Moped::BSON::ObjectId(v)
        when :text
          v = v.to_s
        when :boolean
          v = [true, 'true', 1, '1', 'T', 't'].include?(v.class == String ? v.downcase : v)
        when :raw
          #do nothing
      end
    end
    v
  end

  def date2time(date)
    Time.utc(date.year,date.month,date.day)
  end

end

app/controllers/my/adverts_controller.rb
# coding: utf-8

class My::AdvertsController < My::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs
	before_filter :find_object, :only => [:show, :update, :edit, :destroy]
	before_filter :and_crumbs, :only => [:show, :edit]

	def index
		@adverts = @offer.adverts
	end

	def create
		@type = params[:type]
		@advert = @offer.adverts.build(params[@type.underscore], @type.constantize)
		flash[:notice] = 'Объявление добавлено.' if @advert.save
		respond_with(@advert, :location => offer_advert_path(@offer, @advert))
	end

	def update
		flash[:notice] = 'Объявление обновлено.' if @advert.update_attributes(params[@advert.class.to_s.underscore])
		respond_with(@advert, :location => offer_adverts_path(@offer))
	end

	def destroy
		flash[:notice] = 'Объявление удалено.' if @advert.destroy
		respond_with(@advert, :location => offer_adverts_path(@offer))
	end

  def edit
    @type = @advert.class
  end

  def new
     #@type = params[:type].constantize if params[:type]
     @type = Banner #Temporary hack
 		@advert = @offer.adverts.build({}, @type)
 		add_crumb "Новое объявление"
 	end

	protected

	def find_nested_objects
		@offer = current_user.offers.find(params[:offer_id])
	end

	def and_nested_crumbs
		add_crumb "Рекламные кампании", offers_path
		add_crumb "Рекламная кампания «#{@offer.title}»", offer_path(@offer)
		add_crumb "Объявления", offer_adverts_path(@offer)
	end

	def find_object
		@advert = @offer.adverts.find(params[:id])
	end

	def and_crumbs
		add_crumb "Объявление"
	end
	
end

app/controllers/my/banner_images_controller.rb
# coding: utf-8

class My::BannerImagesController < My::BaseController
	before_filter :find_advert

  def index
    respond_to do |format|
      format.json { render :json => @advert.banner_images.collect { |p| p.to_jq_upload }.to_json }
    end
  end

  def show
    @banner_image = @advert.banner_images.find(params[:id])
    respond_to do |format|
      format.json { render json: @banner_image }
    end
  end

  def new
    @banner_image = @advert.banner_images.new
    respond_to do |format|
      format.json { render json: @banner_image }
    end
  end

	def create
		@banner_image = @advert.banner_images.build(params[:banner_image])
		#if @banner_image.valid?
		#	flash[:notice] = 'valid'
		#else
		#	flash[:error] = 'invalid'
		#end
    respond_to do |format|
      if @banner_image.save
        format.html { redirect_to offer_advert_path(@offer, @advert), notice: 'Изображение добавлено.' }
        format.json { render :json => [ @banner_image.to_jq_upload ].to_json }
      else
        error = @banner_image.errors.messages[:size] ? 'Неверный размер изображения' : @banner_image.errors.full_messages
        format.html { redirect_to offer_advert_path(@offer, @advert), error: error }
        format.json { render :json => [ @banner_image.to_jq_upload.merge({ :error => error }) ].to_json }
      end
    end
	end

	def destroy
    @banner_image = @advert.banner_images.find(params[:id])
    @banner_image.destroy
    respond_to do |format|
      format.html { redirect_to offer_advert_path(@offer, @advert), notice: 'Изображение удалено.' }
      format.json { render :json => true }
    end
 end

  private

	def find_advert
		@offer = current_user.offers.find(params[:offer_id])
		@advert = @offer.adverts.find(params[:advert_id])
	end
	
end

app/controllers/my/base_controller.rb
# coding: utf-8

class My::BaseController < ApplicationController
	respond_to :html
  before_filter :authenticate_user!
  before_filter :check_for_block
	before_filter :get_user_status
	layout 'my'

	add_crumb 'Кабинет', '/'

	def index
    case current_user.class
      when Advertiser, Webmaster
        @common_stat = current_user.common_stats
      when Operator
        redirect_to moderations_url(:subdomain => :admin)
    end
	end

	protected

	def forbid
		render :status => :forbidden, :text => "Forbidden access"
  end

  def check_for_block
    return if self.controller_name == 'base' && self.action_name == 'index'
    if current_user.class==Webmaster && current_user.blocked
      flash[:error] = 'Аккаунт заблокирован'
      redirect_to root_path
    end
  end

	def get_user_status
		@is_operator = (current_user.class==Operator)
	end
end

app/controllers/my/discussions_controller.rb
# coding: utf-8

class My::DiscussionsController < My::BaseController
	before_filter :and_crumbs

	def index
		discussions = current_user.discussions
		@discussions_open = discussions.where(state: :open)
		@discussions_closed = discussions.where(state: :closed)
	end

	def show
		@discussion = Discussion.find(params[:id])
		add_crumb "Дискуссия №#{@discussion.num}: #{@discussion.subject}"
		gon.discussion_id = @discussion.id.to_s
		gon.discussion_last = @discussion.messages.max(:created_at)._dump.unpack('H*').first
		gon.url = request.fullpath
		if params[:last] && !params[:last].empty?
      t = Time._load([params[:last]].pack('H*'))
			@messages = @discussion.messages.where(:created_at.gt => t).order_by([:created_at, :asc])
		end
	end

	def new
		add_crumb "Новая дискуссия"
		@discussion = Discussion.new
		@message = @discussion.messages.new
	end

	def create
		@discussion = Discussion.new(params[:discussion])
		@discussion.user = current_user
		@discussion.messages.first.user = current_user
		flash[:notice] = 'Вопрос добавлен.' if @discussion.save
		respond_with(@discussion, :location => discussion_path(@discussion))
	end

	def message
		@discussion = Discussion.find(params[:discussion_id])
		@message = @discussion.messages.new
		@message.text = params[:text]
		@message.user = current_user
		flash[:notice] = 'Сообщение добавлено.' if @message.save
		respond_with(@message, :location => discussion_path(@discussion))
	end

	def close
		@discussion = Discussion.find(params[:discussion_id])
		flash[:notice] = 'Вопрос закрыт.' if @discussion.update_attribute(:state, :closed)
		respond_with(@discussion, :location => discussion_path(@discussion))
	end

	private

	def and_crumbs
		add_crumb 'Дискуссии', discussions_path
	end

end

app/controllers/my/ground_advert_offers_controller.rb
# coding: utf-8

class My::GroundAdvertOffersController < My::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs

	def index
		@state = (params[:state]) ? params[:state].to_sym : :accepted
    case @state
      when :accepted
        @offers = Offer.any_in(_id: @ground.accepted_rotator_offers_ids).accepted
        add_crumb 'Одобренные офферы'
      when :denied
        @offers = Offer.any_in(_id: @ground.denied_rotator_offers_ids).accepted
        add_crumb 'Отвергнутые офферы'
      when :pending
        @offers = Offer.any_in(_id: @ground.pending_rotator_offers_ids).accepted
        add_crumb 'Ожидающие одобрения офферы'
    end
	end

	def new
		add_crumb 'Новый оффер'
		@offers = Offer.accepted.active.not_in(_id: @ground.advert_offers_ids)
	end

	def create
		@offer = Offer.find(params[:offer_id])
		flash[:notice] = 'Оффер добавлен.' if @ground.add_rotator_offer_and_save(@offer)
		redirect_to ground_adverts_path(@ground)
	end

	def destroy
		@offer = Offer.find(params[:id])
		flash[:notice] = 'Оффер удалён.' if @ground.remove_rotator_offer_and_save(@offer)
		redirect_to ground_adverts_path(@ground)
 	end

	protected

	def find_nested_objects
		@ground = current_user.grounds.find(params[:ground_id])
	end

	def and_nested_crumbs
		add_crumb "Рекламные площадки", grounds_path
		add_crumb "Площадка «#{@ground.title}»", ground_path(@ground)
	end

end

app/controllers/my/ground_link_offers_controller.rb
# coding: utf-8

class My::GroundLinkOffersController < My::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs

	def find_ground
		@ground = current_user.grounds.find(params[:ground_id])
	end

	def index
		@state = (params[:state]) ? params[:state].to_sym : :accepted
		case @state
			when :accepted
				@offers = Offer.any_in(_id: @ground.accepted_link_offers_ids).accepted
				add_crumb 'Одобренные офферы'
			when :denied
				@offers = Offer.any_in(_id: @ground.denied_link_offers_ids).accepted
				add_crumb 'Отвергнутые офферы'
			when :pending
				@offers = Offer.any_in(_id: @ground.pending_link_offers_ids).accepted
				add_crumb 'Ожидающие одобрения офферы'
		end
	end

	def new
		add_crumb 'Новый оффер'
		@offers = Offer.accepted.active.not_in(_id: @ground.link_offers_ids)
  end

  def show
    @offer = Offer.find(params[:id])
    add_crumb 'Одобренные офферы', ground_links_path(@ground, :state => :accepted)
    add_crumb "Оффер #{@offer.title}"
  end

	def create
		@offer = Offer.find(params[:offer_id])
		flash[:notice] = 'Оффер добавлен.' if @ground.add_link_offer_and_save(@offer)
		redirect_to ground_links_path(@ground)
	end

	def destroy
		@offer = Offer.find(params[:id])
		flash[:notice] = 'Оффер удалён.' if @ground.remove_link_offer_and_save(@offer)
		redirect_to ground_links_path(@ground)
 	end

	protected

	def find_nested_objects
		@ground = current_user.grounds.find(params[:ground_id])
	end

	def and_nested_crumbs
		add_crumb "Рекламные площадки", grounds_path
		add_crumb "Площадка «#{@ground.title}»", ground_path(@ground)
	end

end

app/controllers/my/ground_offers_controller.rb
# coding: utf-8

class My::GroundOffersController < My::BaseController
	before_filter :find_nested_objects
	before_filter :and_nested_crumbs
	before_filter :find_object, :only => [:accept, :deny]

	def index
		@ground_offers = @offer.ground_offers
		add_crumb "Рекламные площадки"
	end

	def accept
		@ground_offer = @offer.ground_offers.find(params[:ground_id])
		@ground_offer.state = :accepted
		@ground_offer.save
		flash[:notice] = 'Площадка одобрена.' if @ground_offer.save
		redirect_to offer_grounds_path(@offer)
	end

	def deny
		@ground_offer = @offer.ground_offers.find(params[:ground_id])
		@ground_offer.state = :denied
		flash[:notice] = 'Площадка отклонена.' if @ground_offer.save
		redirect_to offer_grounds_path(@offer)
	end

	protected

	def find_nested_objects
		@offer = current_user.offers.find(params[:offer_id])
	end

	def and_nested_crumbs
		add_crumb "Рекламные кампании", offers_path
		add_crumb "Рекламная кампания «#{@offer.title}»", offer_path(@offer)
	end

	def find_object
		@ground_offer = @offer.ground_offers.find(params[:ground_id])
	end

end

app/views/my/adverts/_form.html.haml
- if @advert.new_record?
	- url =  offer_adverts_path(@offer, :type => @type)
- else
	- url = offer_advert_path(@offer, @advert)

= simple_form_for(@advert, :url => url, :html => {:class => 'form-horizontal' }) do |f|
	-#.control-group= f.input :title, :input_html => { :class => "span6" }
	-#.control-group= f.input :prc_price, :input_html => { :class => "span6" }
	-#.control-group= f.input :fixed_price, :input_html => { :class => "span6" }
	-#= f.input :_type, :as => :hidden, :input_html => { :value => type.capitalize }
	- case @type
		- when Banner
			%b= 'Укажите ссылку на страницу, куда будет переходить посетитель при клике на банер:'
			%br
			%br
			= f.input :url, :input_html => { :class => "span6" }, :placeholder => 'http://'
			= f.input :description, :as => :text, :input_html => { :class => "span6" }
			-#%p= "Пожалуйста, загрузите изображение одного из следующих размеров: #{ADVERTS_SIZES.to_sentence}:"
			-#.control-group= f.input :url, :input_html => { :class => "span6" }
	= f.button :submit, :class => 'btn-primary'
	= link_to 'Отмена', offer_adverts_path, :class => "btn btn-danger"

app/views/my/adverts/_templates.html.erb
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview">
      <span class="fade"></span>
    </td>
    <td><span class="label label-info">Новый</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td>
        <div class="start">{% if (!o.options.autoUpload) { %}
          <button class="btn btn-primary btn-small">
            <i class="icon-upload icon-white"></i>
            <span>Загрузить</span>
          </button>
          {% } %}</div>
        {% } %}
        <div class="cancel">{% if (!i) { %}
          <button class="btn btn-warning btn-small">
            <i class="icon-ban-circle icon-white"></i>
            <span>Отмена</span>
          </button>
          {% } %}</div>
    </td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td class="error" colspan="4"><span class="label label-important">Ошибка</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
       {% } else { %}
        <td class="preview">{% if (file.url) { %}<img src="{%=file.url%}">{% } %}</td>
        <td><span class="label ">Ожидание</span></td>
        <td class="size"><span>{%=file.size%}</span></td>
        <td></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>Удалить</span>
        </button>
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      $('#fileupload').fileupload();
  });
</script>

app/views/my/adverts/index.html.haml
%table.table.table-bordered.table-striped
	%thead
		%tr
			%th= 'Предпросмотр'
			%th= 'Статус'
			%th= 'Тип'
			%th= 'Размеры'
			%th= 'Дополнительно'
			%th= 'Действия'
	%tbody
		- @adverts.each do |advert|
			%tr{:class => advert.is_accepted? ? '' : 'muted'}
				%td
					- unless advert.banner_images.empty?
						- img = advert.banner_images.first.image
						- if img.present?
							%ul.thumbnails
								%li.span3
									.thumbnail= image_tag img
				%td= state_label advert.moderated_state
				%td=t "model.#{advert._type}"
				%td= advert.sizes.to_sentence
				%td
					- case advert.class
						- when Banner
							= "URL: #{advert.url}"
				%td
					= link_to offer_advert_path(@offer, advert), :class => 'btn btn-small' do
						%i.icon-pencil
						= 'Редактировать'
					= link_to offer_advert_path(@offer, advert), :class => 'btn btn-small btn-danger', :method => :delete, :data => { :confirm => "Вы уверены?"} do
						%i.icon-trash.icon-white
						= 'Удалить'
= link_to new_offer_advert_path(@offer), :class => 'btn btn-primary' do
	%i.icon-plus-sign.icon-white
	= 'Добавить'

app/views/my/adverts/new.html.haml
- unless @type
	%h2= 'Выбор типа объявления'
	= link_to new_offer_advert_path(@offer, :type => Banner.name), :class => 'btn btn-primary' do
		%i.icon-picture.icon-white
		= 'Банер'
	= link_to new_offer_advert_path(@offer, :type => Banner.name), :class => 'btn btn-primary' do
		%i.icon-picture.icon-white
		= 'Банер'
	= link_to new_offer_advert_path(@offer, :type => Banner.name), :class => 'btn btn-primary' do
		%i.icon-picture.icon-white
		= 'Банер'
- else
	= render 'form'

app/views/my/adverts/show.html.haml
- case @advert.class
	- when Banner
		%p
			%b= 'URL: '
			= @advert.url
			= link_to '(редактировать)', edit_offer_advert_path(@offer, @advert)
			- if @advert.description
				%br
				%b= 'Описание: '
				= @advert.description
%hr
- case @advert.class
	- when Banner
		%h2= 'Изображения'
		#fileupload
			%table.table.table-bordered.table-striped
				%thead
					%tr
						%th= 'Предпросмотр'
						%th= 'Статус'
						%th= 'Размер'
						%th= 'Дополнительно'
						%th= 'Действия'
				%tbody.files
					- @advert.banner_images.each do |banner_image|
						%tr{:class => banner_image.is_accepted? ? '' : 'muted'}
							%td
								- if banner_image.image.present?
									%ul.thumbnails
										%li.span3
											.thumbnail= image_tag banner_image.image
							%td= state_label banner_image.moderated_state
							%td= banner_image.size
							%td
								= 'Создано автоматически' if banner_image.auto_generated
							%td
								= link_to offer_advert_banner_image_path(@offer, @advert, banner_image), :class => 'btn btn-small btn-danger', :method => :delete, :data => { :confirm => "Вы уверены?"} do
									%i.icon-trash.icon-white
									= 'Удалить'

			= form_for @advert.banner_images.new, :url => offer_advert_banner_images_path(@offer, @advert), :html => { :multipart => true } do |f|
				.row.fileupload-buttonbar
					.span6
						%span.btn.btn-success.fileinput-button
							%i.icon-plus.icon-white
							%span Добавить изображения...
							= f.file_field :image, multiple: true, name: 'banner_image[image]'
						%button.btn.btn-primary.start{:type => "submit"}
							%i.icon-upload.icon-white
							Начать загрузку
					.span3
						.progress.progress-success.progress-striped.active.fade
							.bar{:style => "width:0%;"}
						.fileupload-loading


		= render :partial => 'templates'
		%p
			= 'Загрузите изображения следующих размеров: '
			= ADVERTS_SIZES.to_sentence

		%br
		%hr
		Если по каким-то причинам у вас не работает современная форма загрузки, вы можете воспользоваться классической формой:
		%br
		= simple_form_for(@advert.banner_images.new, :url => offer_advert_banner_images_path(@offer, @advert), :html => {:class => 'form-inline' }) do |f|
			= f.input :image, :as => :file, :input_html => { :class => "inline" }, :wrapper_html => { :class => "inline" }
			= f.button :submit, :class => 'btn'